spring.application.name=api-clientes

server.port=8081

database.host=jdbc:postgresql://localhost:5432/bdclientes
database.users=postgres
database.pass=coti

cors.allowed=http://localhost:4200,htpp://localhost:3000
